/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package conversorpdf;

import conversorpdf.Conversor.Conversor;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author marcus
 */
public class TelaPrincipal extends javax.swing.JFrame {

    protected File arquivoSelecionado;
    
    protected conversorpdf.Conversor.Conversor conversor;
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
         setLocationRelativeTo( null ); 
        this.conversor = new Conversor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        JbuttonSelecionarPDF = new javax.swing.JButton();
        jLabelArquivoSelecionado = new javax.swing.JLabel();
        jButtonConverter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor de PDF para TXT");
        setResizable(false);

        JbuttonSelecionarPDF.setText("Selecionar Arquivo PDF");
        JbuttonSelecionarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbuttonSelecionarPDFActionPerformed(evt);
            }
        });

        jLabelArquivoSelecionado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelArquivoSelecionado.setText("Selecionar Arquivo");

        jButtonConverter.setText("Converter para TXT");
        jButtonConverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConverterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonConverter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelArquivoSelecionado, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                    .addComponent(JbuttonSelecionarPDF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelArquivoSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JbuttonSelecionarPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonConverter, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbuttonSelecionarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbuttonSelecionarPDFActionPerformed

        JFileChooser chooser = new JFileChooser();
        chooser.setMultiSelectionEnabled(false);
        
        if( chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION)
        {
         this.arquivoSelecionado = chooser.getSelectedFile();
         
         this.jLabelArquivoSelecionado.setText(this.arquivoSelecionado.getName());
        }
         
         
        
        
    }//GEN-LAST:event_JbuttonSelecionarPDFActionPerformed

    private void jButtonConverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConverterActionPerformed
        
        if(this.arquivoSelecionado == null ||  !this.arquivoSelecionado.isFile())
        {
            JOptionPane.showMessageDialog(this, "Nenhum arquivo Selecionado!");
            return;
        }
        
        JFileChooser salvar = new JFileChooser();
        salvar.setMultiSelectionEnabled(false);
        salvar.setSelectedFile(new File("Arquivo.txt"));
        
        if( salvar.showSaveDialog(this) == JFileChooser.APPROVE_OPTION)
        {
                try
                {
                    File f = salvar.getSelectedFile();
                    this.conversor.parsePdf(this.arquivoSelecionado.getAbsolutePath(), f.getAbsolutePath());
                    JOptionPane.showMessageDialog(this, "Arquivo convertido com sucesso!");
                }
                catch(IOException e)
                {
                    JOptionPane.showMessageDialog(this, "Não foi possivel converter o arquivo erro informado:\n"+e.toString());
                }
        }
        
    }//GEN-LAST:event_jButtonConverterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbuttonSelecionarPDF;
    private javax.swing.JButton jButtonConverter;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabelArquivoSelecionado;
    // End of variables declaration//GEN-END:variables
}
